apiVersion: v1
kind: Service
metadata:
  name: danak_backend
  namespace: default
  labels:
    app: danak_backend
spec:
  selector:
    app: danak_backend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
