apiVersion: apps/v1
kind: Deployment
metadata:
  name: danak_backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danak_backend
      version: 'v1'
  template:
    metadata:
      labels:
        app: danak_backend
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - danak_backend
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 danak_backend-mongodb 27017)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: danak_backend-app
          image: danakdhub/danak_backend
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SPRING_DATA_MONGODB_DATABASE
              value: danak_backend
            - name: SPRING_DATA_MONGODB_URI
              value: 'mongodb://danak_backend-mongodb-0.danak_backend-mongodb.default:27017/?waitQueueMultiple=1000,danak_backend-mongodb-1.danak_backend-mongodb.default:27017/?waitQueueMultiple=1000,danak_backend-mongodb-2.danak_backend-mongodb.default:27017/?waitQueueMultiple=1000'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
            - name: SERVER_SHUTDOWN
              value: graceful
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
