apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: danakdhub/danak_backend
      context: ../danak--new-tech
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
